/**
 * File & Image Generation Service
 *
 * Generates PDFs, DOCX, PPTX documents and DALL-E 3 images.
 * Files are saved to /uploads/generated/ and served via static route.
 */

import OpenAI from "openai";
import PDFDocument from "pdfkit";
import PptxGenJS from "pptxgenjs";
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from "docx";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { uploadToCloudinary } from "../utils/cloudinary.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

let openai;
const getClient = () => {
    if (!openai) openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
    return openai;
};

// Ensure output directory exists
const OUTPUT_DIR = path.join(__dirname, "../../uploads/generated");
if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

/**
 * Generate structured content via GPT-4o for documents
 */
const generateContent = async (topic, docType) => {
    const client = getClient();

    const prompts = {
        pdf: `Create a well-structured document about: "${topic}". 
Format your response as JSON with this structure:
{ "title": "...", "sections": [{ "heading": "...", "content": "paragraph text..." }] }
Include 4-6 sections with clear headings and detailed content. ONLY return valid JSON.`,

        docx: `Create a detailed document about: "${topic}". 
Format your response as JSON with this structure:
{ "title": "...", "sections": [{ "heading": "...", "content": "paragraph text..." }] }
Include 4-6 sections with clear headings and detailed paragraphs. ONLY return valid JSON.`,

        pptx: `Create a presentation about: "${topic}". 
Format your response as JSON with this structure:
{ "title": "...", "slides": [{ "title": "...", "bullets": ["point 1", "point 2", "point 3"] }] }
Include 5-8 slides with clear titles and 3-4 bullet points each. ONLY return valid JSON.`,
    };

    const response = await client.chat.completions.create({
        model: "gpt-4o",
        messages: [
            { role: "system", content: "You are a document content generator. Return ONLY valid JSON, no markdown fences." },
            { role: "user", content: prompts[docType] || prompts.pdf },
        ],
        temperature: 0.7,
        max_tokens: 2000,
    });

    const raw = response.choices[0].message.content?.trim();
    const cleaned = raw.replace(/```json\n?/g, "").replace(/```\n?/g, "").trim();
    return JSON.parse(cleaned);
};

/**
 * Generate a PDF document
 */
export const generatePDF = async (topic) => {
    const content = await generateContent(topic, "pdf");
    const fileName = `${Date.now()}_${topic.slice(0, 30).replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;
    const filePath = path.join(OUTPUT_DIR, fileName);

    return new Promise((resolve, reject) => {
        const doc = new PDFDocument({ margin: 60, size: "A4" });
        const stream = fs.createWriteStream(filePath);
        doc.pipe(stream);

        // Title
        doc.fontSize(24).font("Helvetica-Bold").fillColor("#1a1a2e")
            .text(content.title, { align: "center" });
        doc.moveDown(0.5);
        doc.fontSize(10).font("Helvetica").fillColor("#6B7280")
            .text(`Generated on ${new Date().toLocaleDateString("en-IN")}`, { align: "center" });
        doc.moveDown(1);

        // Divider
        doc.strokeColor("#E5E7EB").lineWidth(1)
            .moveTo(60, doc.y).lineTo(535, doc.y).stroke();
        doc.moveDown(1);

        // Sections
        for (const section of content.sections) {
            doc.fontSize(16).font("Helvetica-Bold").fillColor("#2d2d44")
                .text(section.heading);
            doc.moveDown(0.3);
            doc.fontSize(11).font("Helvetica").fillColor("#374151")
                .text(section.content, { lineGap: 4 });
            doc.moveDown(1);
        }

        // Footer
        doc.moveDown(2);
        doc.fontSize(8).fillColor("#9CA3AF")
            .text("Generated by AI Companion", { align: "center" });

        doc.end();

        stream.on("finish", async () => {
            // Serve directly from backend /files/ route (Cloudinary raw access is restricted)
            resolve({ fileName, filePath, title: content.title, cloudinaryUrl: null });
        });
        stream.on("error", reject);
    });
};

/**
 * Generate a DOCX document
 */
export const generateDOCX = async (topic) => {
    const content = await generateContent(topic, "docx");
    const fileName = `${Date.now()}_${topic.slice(0, 30).replace(/[^a-zA-Z0-9]/g, "_")}.docx`;
    const filePath = path.join(OUTPUT_DIR, fileName);

    const sections = [];

    // Title
    sections.push(
        new Paragraph({
            children: [new TextRun({ text: content.title, bold: true, size: 48, color: "1a1a2e" })],
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            spacing: { after: 200 },
        })
    );

    // Date
    sections.push(
        new Paragraph({
            children: [new TextRun({ text: `Generated on ${new Date().toLocaleDateString("en-IN")}`, size: 20, color: "6B7280", italics: true })],
            alignment: AlignmentType.CENTER,
            spacing: { after: 400 },
        })
    );

    // Content sections
    for (const section of content.sections) {
        sections.push(
            new Paragraph({
                children: [new TextRun({ text: section.heading, bold: true, size: 32, color: "2d2d44" })],
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 300, after: 150 },
            })
        );
        sections.push(
            new Paragraph({
                children: [new TextRun({ text: section.content, size: 24, color: "374151" })],
                spacing: { after: 200, line: 360 },
            })
        );
    }

    const doc = new Document({
        sections: [{ children: sections }],
    });

    const buffer = await Packer.toBuffer(doc);
    fs.writeFileSync(filePath, buffer);

    // Serve directly from backend /files/ route (Cloudinary raw access is restricted)
    return { fileName, filePath, title: content.title, cloudinaryUrl: null };
};

/**
 * Generate a PPTX presentation
 */
export const generatePPTX = async (topic) => {
    const content = await generateContent(topic, "pptx");
    const fileName = `${Date.now()}_${topic.slice(0, 30).replace(/[^a-zA-Z0-9]/g, "_")}.pptx`;
    const filePath = path.join(OUTPUT_DIR, fileName);

    const pptx = new PptxGenJS();
    pptx.layout = "LAYOUT_WIDE";

    // Title slide
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: "1a1a2e" };
    titleSlide.addText(content.title, {
        x: 0.5, y: 1.5, w: "90%", h: 2,
        fontSize: 36, color: "FFFFFF", bold: true,
        align: "center", valign: "middle",
    });
    titleSlide.addText(`Generated on ${new Date().toLocaleDateString("en-IN")}`, {
        x: 0.5, y: 4, w: "90%", h: 0.5,
        fontSize: 14, color: "9CA3AF", align: "center",
    });

    // Content slides
    for (const slide of content.slides) {
        const s = pptx.addSlide();
        s.background = { color: "0f0f23" };

        s.addText(slide.title, {
            x: 0.5, y: 0.3, w: "90%", h: 1,
            fontSize: 28, color: "C084FC", bold: true,
        });

        const bulletsText = slide.bullets.map((b, i) => ({
            text: b,
            options: {
                fontSize: 18, color: "E5E7EB",
                bullet: { code: "2022" },
                breakLine: true,
                paraSpaceAfter: 8,
            },
        }));

        s.addText(bulletsText, {
            x: 0.8, y: 1.5, w: "85%", h: 3.5,
        });
    }

    await pptx.writeFile({ fileName: filePath });

    // Serve directly from backend /files/ route (Cloudinary raw access is restricted)
    return { fileName, filePath, title: content.title, cloudinaryUrl: null };
};

/**
 * Generate an image via DALL-E 3
 */
export const generateImage = async (prompt) => {
    const client = getClient();
    const fileName = `${Date.now()}_image.png`;
    const filePath = path.join(OUTPUT_DIR, fileName);

    const response = await client.images.generate({
        model: "dall-e-3",
        prompt: prompt,
        n: 1,
        size: "1024x1024",
        quality: "standard",
    });

    const imageUrl = response.data[0].url;

    const imageResponse = await fetch(imageUrl);
    const arrayBuffer = await imageResponse.arrayBuffer();
    const buffer = Buffer.from(arrayBuffer);
    fs.writeFileSync(filePath, buffer);

    const cloudinaryUrl = await uploadToCloudinary(filePath, "ai_mvp_images");

    return {
        fileName,
        filePath,
        url: imageUrl, // temporary OpenAI URL
        cloudinaryUrl,
        revisedPrompt: response.data[0].revised_prompt,
    };
};
